name: Azure PowerShell Automation
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    paths:
    - src/automation-demo
  schedule:
  - cron: '0 */12 * * *'

permissions:
  id-token: write
  contents: read
  
jobs:
  Automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # https://github.com/Azure/login
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Automation
      uses: azure/powershell@v2
      with:
        inlineScript: src/automation-demo/run.ps1
        azPSVersion: latest
        errorActionPreference: stop
        failOnStandardError: true
                    
